// Generated by gencpp from file server_test/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SERVER_TEST_MESSAGE_ADDTWOINTS_H
#define SERVER_TEST_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <server_test/AddTwoIntsRequest.h>
#include <server_test/AddTwoIntsResponse.h>


namespace server_test
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace server_test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::server_test::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::server_test::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::server_test::AddTwoInts > {
  static const char* value()
  {
    return "server_test/AddTwoInts";
  }

  static const char* value(const ::server_test::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::server_test::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::server_test::AddTwoInts > 
template<>
struct MD5Sum< ::server_test::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::server_test::AddTwoInts >::value();
  }
  static const char* value(const ::server_test::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::server_test::AddTwoIntsRequest> should match 
// service_traits::DataType< ::server_test::AddTwoInts > 
template<>
struct DataType< ::server_test::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::server_test::AddTwoInts >::value();
  }
  static const char* value(const ::server_test::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::server_test::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::server_test::AddTwoInts > 
template<>
struct MD5Sum< ::server_test::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::server_test::AddTwoInts >::value();
  }
  static const char* value(const ::server_test::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::server_test::AddTwoIntsResponse> should match 
// service_traits::DataType< ::server_test::AddTwoInts > 
template<>
struct DataType< ::server_test::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::server_test::AddTwoInts >::value();
  }
  static const char* value(const ::server_test::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVER_TEST_MESSAGE_ADDTWOINTS_H
